### ISSUE TITLE
Create room status responses

### ISSUE THREAD

**Issue by NiebieskiRekin** [akai-org/mafiakai#14]
Whenever a player intends to join a room they shall be given a brief description of the game status, namely:

- the current number of players in this room
- the phase of the game (please have a look at /types/Game.ts)

Example json API request/response flow

- request:
  `GET /room/1234`
- response:

  ```json
  {
    "num_players": 3,
    "phase": "LOBBY"
  }

**Comment by erybie222** [comment]
ja to chętnie zrobie
