### ISSUE TITLE
Chore: project config

### ISSUE THREAD

**Issue by Aleks334** [akai-org/mafiakai#5]
- [x] add prettier config file
- [x] handle absolute paths (for imports) in vite

**Comment by Aleks334** [comment]
@mit3r I think that we should move prettier config to the root dir of project, as it can be shared across frontend and backend. Unfortunately putting it in root dir doesn't work (config isn't used in client/server). I consider that we can use for example npm workspaces in root project to handle this (and common types too). Alternatively we can stick to the current version and manage prettier in frontend, backend separately. What do you think about it?

**Comment by mit3r** [comment]
@Aleks334 My fault. In main dir in package.json has "prettier" configuration - delete it. And add .prettierrc in main dir with 
```json
{
    "filepath": "{client,server}/**/.{js,jsx,ts,tsx,md}"
}
```

**Comment by Aleks334** [comment]
It works now. Thanks
