### ISSUE TITLE
Write Phases enum

### ISSUE THREAD

**Issue by mit3r** [akai-org/mafiakai#8]
Write enum type to handle all of game phases. You should also suggest conditions for moving to the next state in the comments. 

Enum type should be in global types directory, both backend and frontend need it.

At best enums should be written as 
```typescript 
enum Phases {
    VOTING = "voting" or "VOTING"
    // so on
 }
 ```

**Comment by erybie222** [comment]
1.POSITION SELECTION
2. if all players are ready then CHARACTER SELECTION
3.if all players are ready then ROLE ASSGINMENT
4.after certain time WELCOME
5. after certain time ROUND_START
6. after certain time DAY
7. after certain time DEBATE
8. after certain time VOTING
9. if two or more people got the same amount of votes (the most) then VOTING_OVERTIME
10. after certain time NIGHT
11. then BODYGUARD_DEFENSE
12. if bodyguard chose the person , DETECTIVE_CHECK
13. if detective chose the person then MAFIA_VOTING
14. if mavia voted or certain time limit passed then ROUND_END
15. if no mafia members anymore or mafia members>citizens  then GAME_END

**Comment by erybie222** [comment]
fuck, should I put the comments into code?

**Comment by mit3r** [comment]
Yes, but nothing is lost, just make additional commits
